In [16]:
import numpy as np
from pupil_labs.realtime_api.simple import discover_one_device

import time

from datetime import datetime
import matplotlib.pyplot as plt
import cv2

import nest_asyncio
nest_asyncio.apply()

In [17]:
device = discover_one_device()

print(f"Phone IP address: {device.phone_ip}")
print(f"Phone name: {device.phone_name}")
print(f"Battery level: {device.battery_level_percent}%")
print(f"Free storage: {device.memory_num_free_bytes / 1024**3:.1f} GB")
print(f"Serial number of connected module: {device.module_serial}")

Phone IP address: 192.168.1.172
Phone name: Neon Companion
Battery level: 8%
Free storage: 213.9 GB
Serial number of connected module: 619453


In [18]:
recording_id = device.recording_start()
print(f"Started recording with id {recording_id}")

time.sleep(5)

device.recording_stop_and_save()

Started recording with id 8eebd26b-493a-4b09-ba95-4edc5de6a225


In [3]:
device.recording_start()

print(device.send_event("python test event 1"))

time.sleep(5)

# send event with current timestamp
print(device.send_event("python test event 2", event_timestamp_unix_ns=time.time_ns()))

device.recording_stop_and_save()

Event(name=None recording_id=26ca4aaf-c66d-46f7-b9fc-5f36e1e6f37f timestamp_unix_ns=1706476270542000000 datetime=2024-01-28 22:11:10.542000)
Event(name=None recording_id=327902ee-52c4-4019-a028-99a23ec69bf3 timestamp_unix_ns=1706476275453132057 datetime=2024-01-28 22:11:15.453132)


In [5]:
device.send_event("python test event 2", time.time_ns())

Event(name=None recording_id=None timestamp_unix_ns=1706476290329195068 datetime=2024-01-28 22:11:30.329195)

In [ ]:
scene_sample, gaze_sample = device.receive_matched_scene_video_frame_and_gaze()

scene_image_rgb = cv2.cvtColor(scene_sample.bgr_pixels, cv2.COLOR_BGR2RGB)
plt.imshow(scene_image_rgb)
plt.scatter(gaze_sample.x, gaze_sample.y, s=200, facecolors='none', edgecolors='r')

In [20]:
imu_sample = device.receive_imu_datum()

dt = datetime.fromtimestamp(imu_sample.timestamp_unix_seconds)
print(f"This IMU sample was recorded at {dt}")

print(f"It contains the following data:")

print(f"Head pose:")
print(imu_sample.quaternion)

print(f"Acceleration data:")
print(imu_sample.accel_data)

print(f"Gyro data:")
print(imu_sample.gyro_data)

This IMU sample was recorded at 2024-02-01 21:59:20.576239
It contains the following data:
Head pose:
Quaternion(x=0.6530987024307251, y=0.7547710537910461, z=0.009617586620151997, w=0.060259804129600525)
Acceleration data:
Data3D(x=-0.0742187425494194, y=0.09130859375, z=-1.00244140625)
Gyro data:
Data3D(x=-0.02288818359375, y=-0.171661376953125, z=-0.2307891845703125)


In [15]:
from datetime import timezone

print(datetime(2020, 11, 1, 8, tzinfo=timezone.utc).astimezone(ZoneInfo("America/New_York")))
print(datetime(2020, 11, 1, 8, tzinfo=timezone.utc).astimezone(ZoneInfo("Europe/Berlin")))
print(datetime(2020, 11, 1, 8, tzinfo=timezone.utc).astimezone(ZoneInfo("Asia/Hong_Kong")))

2020-11-01 03:00:00-05:00
2020-11-01 09:00:00+01:00
2020-11-01 16:00:00+08:00


In [23]:
import zoneinfo
from zoneinfo import ZoneInfo
zoneinfo.available_timezones()

{'Africa/Abidjan',
 'Africa/Accra',
 'Africa/Addis_Ababa',
 'Africa/Algiers',
 'Africa/Asmara',
 'Africa/Asmera',
 'Africa/Bamako',
 'Africa/Bangui',
 'Africa/Banjul',
 'Africa/Bissau',
 'Africa/Blantyre',
 'Africa/Brazzaville',
 'Africa/Bujumbura',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Conakry',
 'Africa/Dakar',
 'Africa/Dar_es_Salaam',
 'Africa/Djibouti',
 'Africa/Douala',
 'Africa/El_Aaiun',
 'Africa/Freetown',
 'Africa/Gaborone',
 'Africa/Harare',
 'Africa/Johannesburg',
 'Africa/Juba',
 'Africa/Kampala',
 'Africa/Khartoum',
 'Africa/Kigali',
 'Africa/Kinshasa',
 'Africa/Lagos',
 'Africa/Libreville',
 'Africa/Lome',
 'Africa/Luanda',
 'Africa/Lubumbashi',
 'Africa/Lusaka',
 'Africa/Malabo',
 'Africa/Maputo',
 'Africa/Maseru',
 'Africa/Mbabane',
 'Africa/Mogadishu',
 'Africa/Monrovia',
 'Africa/Nairobi',
 'Africa/Ndjamena',
 'Africa/Niamey',
 'Africa/Nouakchott',
 'Africa/Ouagadougou',
 'Africa/Porto-Novo',
 'Africa/Sao_Tome',
 'Africa/Timbuktu',
 'Africa/

In [28]:
from dateutil import tz

tz.gettz("EDT")

/usr/lib/python3/dist-packages/dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
  warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))


Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectio

In [41]:
from zoneinfo import ZoneInfo
from datetime import datetime, timedelta

dt_utc = datetime.fromtimestamp(imu_sample.timestamp_unix_seconds, ZoneInfo("UTC"))
dt1 = datetime.fromtimestamp(imu_sample.timestamp_unix_seconds, ZoneInfo("EST"))
dt2 = dt1 + timedelta(hours=1)

dt_est = dt_utc - timedelta(hours=5)
dt_edt = dt_utc - timedelta(hours=4)

print(dt_utc)
print(dt_est)
print(dt1)
print(dt_edt)
print(dt2)


2024-02-01 20:59:20.576239+00:00
2024-02-01 16:59:20.576239+00:00
2024-02-01 15:59:20.576239-05:00
2024-02-01 16:59:20.576239+00:00
2024-02-01 16:59:20.576239-05:00


Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectionError('Unable to connect to 192.168.1.172:8086'). Reconnecting...
Error on stream: RTSPConnectio

In [11]:
calibration = device.get_calibration()

print("Scene camera matrix:")
print(calibration["scene_camera_matrix"][0])
print("\nScene distortion coefficients:")
print(calibration["scene_distortion_coefficients"][0])

print("\nRight camera matrix:")
print(calibration["right_camera_matrix"][0])
print("\nRight distortion coefficients:")
print(calibration["right_distortion_coefficients"][0])

print("\nLeft camera matrix:")
print(calibration["left_camera_matrix"][0])
print("\nLeft distortion coefficients:")
print(calibration["left_distortion_coefficients"][0])

Scene camera matrix:
[[885.15825992   0.         824.12887524]
 [  0.         885.14923875 612.28065252]
 [  0.           0.           1.        ]]

Scene distortion coefficients:
[-0.13053092  0.10917948 -0.0001823  -0.00043524  0.00068462  0.17075814
  0.05227603  0.02661005]

Right camera matrix:
[[139.37418637   0.          99.23202584]
 [  0.         139.35188665  96.19039145]
 [  0.           0.           1.        ]]

Right distortion coefficients:
[ 3.68394045e-02 -1.23725784e-01  1.05156082e-03 -6.51159021e-04
 -6.49958070e-01 -5.22825142e-02  9.73858508e-03 -6.94081020e-01]

Left camera matrix:
[[139.02147562   0.          93.94689674]
 [  0.         139.25351257  96.6396657 ]
 [  0.           0.           1.        ]]

Left distortion coefficients:
[ 0.05170779 -0.11790007 -0.00186199  0.00106443 -0.60876161 -0.04746648
  0.02421155 -0.65088475]


In [12]:
device.receive_gaze_datum()

GazeData(x=821.1923828125, y=488.2939453125, worn=True, timestamp_unix_seconds=1706523169.8227248)

In [ ]:
t = []
for i in range(1000):
    st = time.perf_counter()
    device.receive_gaze_datum()
    est = time.perf_counter()
    t.append(est - st)

[np.mean(t), np.median(t)]

[0.005303709819008873, 0.004529576500317489]

Stopping run loop for rtsp://192.168.1.172:8086/?camera=world
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received for 10 seconds: closing
no RTP received fo

In [13]:
estimate = device.estimate_time_offset()
print(f"Mean time offset: {estimate.time_offset_ms.mean} ms")
print(f"Mean roundtrip duration: {estimate.roundtrip_duration_ms.mean} ms")

Mean time offset: -1836.67 ms
Mean roundtrip duration: 6.34 ms
